### ISSUE TITLE
Broken with latest SDK3?

### ISSUE THREAD

**Issue by seanidzenga** [llealloo/vrc-udon-audio-link#55]
AudioLink 0.2.4 seems to be broken on VRC SDK3-WORLD-2021.05.21.12.13_Public

I'm getting quite a few errors in the console and they're preventing the VRC SDK from building:

```
Assembly 'Assets/Udon/Editor/External/VRC.Udon.Compiler.dll' will not be loaded due to errors:
Reference has errors 'VRC.Udon.Graph'.

Assembly 'Assets/Udon/Editor/External/VRC.Udon.EditorBindings.dll' will not be loaded due to errors:
Unable to resolve reference 'Cinemachine'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'Unity.TextMeshPro'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

Assembly 'Assets/Udon/Editor/External/VRC.Udon.Graph.dll' will not be loaded due to errors:
Unable to resolve reference 'Cinemachine'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'Unity.TextMeshPro'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

Assembly 'Assets/Udon/Editor/External/VRC.Udon.VRCGraphModules.dll' will not be loaded due to errors:
Reference has errors 'VRC.Udon.Graph'.
```

**Comment by seanidzenga** [comment]
Rolling back to v0.2.3 resolves the issue

**Comment by seanidzenga** [comment]
Tried again today after - after dropping some initial errors that appeared after import I'm left with

```
Assets\3rd-Party\AudioLink\Scripts\AudioLink.cs(126,17): error CS0103: The name 'RequestSerialization' does not exist in the current context
```

**Comment by Earthstorm** [comment]
I'm also encountering this error when using v0.2.4

**Comment by OrbitalRing** [comment]
I am getting issues with audio reactive lights, but reactive materials work fine on 2.4. The controller and listener work fine too, so it is receiving audio input. For me 2.2 still works on another world, so I'm reverting to 2.3 as suggested here until further notice. Thanks for writing this up!

**Comment by llealloo** [comment]
@seanidzenga sounds like your Udon Sharp is out of date

**Comment by llealloo** [comment]
@OrbitalRing can you make a separate issue?

**Comment by llealloo** [comment]
Great to hear and no worries! That happens all the time actually :)
